config/routes.rb
Rails.application.routes.draw do
  
  mount_opro_oauth
  
  devise_for :admins

   root 'plainpage#home'
   resources :plainpage
   resources :settings
   resources :users
   resources :user_devices
   resources :beacons
   resources :admins
   resources :histories do
     collection do
      get :search
     end
   end
   
   namespace :api, defaults: {format: 'json'} do
    namespace :v1 do
      resources :beacons
      resources :histories do
        collection do
          post :log
        end
      end
      resources :users do
        collection do
          post :logout
        end
      end
    end
  end

end

app/views/partials/_footer.html.erb
<!-- footer content -->
<footer>
  <div class="pull-right">
    Gentelella - Bootstrap Admin Template by <a href="https://colorlib.com">Colorlib</a>
  </div>
  <div class="clearfix"></div>
</footer>
<!-- /footer content -->
</div>
</div>

<div id="custom_notifications" class="custom-notifications dsp_none">
  <ul class="list-unstyled notifications clearfix" data-tabbed_notifications="notif-group">
  </ul>
  <div class="clearfix"></div>
  <div id="notif-group" class="tabbed_notifications"></div>
</div>

app/views/partials/_sidenav.html.erb
<div class="main_container">

  <div class="col-md-3 left_col">
    <div class="left_col scroll-view">

      <div class="navbar nav_title" style="border: 0;background: #F5F5F5;">
        <a href="<%= root_path %>" class="site_title cus_logo"><%= image_tag "logo.png"%></a>
      </div>
      <div class="clearfix"></div>


      <!-- menu profile quick info -->
      <div class="profile">
        <div class="profile_pic">
        
          <%= image_tag request.base_url + current_admin.photo.url, :class => "img-circle profile_img"  %>
        </div>
        <div class="profile_info">
          <span>Welcome,</span>
          <h2><%= current_admin.first_name.titleize %></h2>
        </div>
      </div>
      <!-- /menu profile quick info -->

      <br />

      <!-- sidebar menu -->
      <div id="sidebar-menu" class="main_menu_side hidden-print main_menu" style="margin-top: 100px;">

        <div class="menu_section">
          
          <ul class="nav side-menu">
            <li><a href="<%= root_path %>"><i class="fa fa-home"></i> Home</a>
             
            </li>
            <li><a href="<%= users_url %>"><i class="fa fa-user"></i> Users </a>
              
            </li>
            <li><a href="<%= user_devices_url %>"><i class="fa fa-mobile"></i> User Devices </a>
              
            </li>
            <li><a href="<%= beacons_url %>"><i class="fa fa-bullseye"></i> Beacons </a>
              
            </li>
            <li><a href="<%= histories_url %>"><i class="fa fa-history" ></i> History </span></a>
             
            </li><% @timer = RssiTimer.find(1) %>
            <li><a href="<%= edit_setting_path(@timer) %>"><i class=" fa fa-cog" ></i> Setting </span></a>
             
            </li>
          </ul>
        </div>
  
      </div>
      <!-- /sidebar menu -->

      <!-- /menu footer buttons -->
      
      <!-- /menu footer buttons -->
    </div>
  </div>

app/views/partials/_topnav.html.erb
<!-- top navigation -->
<div class="top_nav">

  <div class="nav_menu">
    <nav class="" role="navigation">
      <div class="nav toggle">
        <a id="menu_toggle"><i class="fa fa-bars"></i></a>
      </div>

      <ul class="nav navbar-nav navbar-right">
        <li class="">
          <a href="javascript:;" class="user-profile dropdown-toggle" data-toggle="dropdown" aria-expanded="false">
            <%= image_tag request.base_url + current_admin.photo.url %>Admin
            <span class=" fa fa-angle-down"></span>
          </a>
          <ul class="dropdown-menu dropdown-usermenu pull-right">
            <li><%= link_to 'Edit Profile', edit_admin_path(current_admin),  style: "margin-right: 10px;" %>
            </li>
            <li>
             <%= link_to '<i class="fa fa-sign-out pull-right"></i> Log Out'.html_safe, destroy_admin_session_path, method: :delete %>
            </li>
          </ul>
        </li>

      </ul>
    </nav>
  </div>

</div>
<!-- /top navigation -->