config/routes.rb
Rails.application.routes.draw do
  
  mount_opro_oauth
  
  devise_for :admins

   root 'plainpage#home'
   resources :plainpage
   resources :settings
   resources :users
   resources :user_devices
   resources :beacons
   resources :admins
   resources :histories do
     collection do
      get :search
     end
   end
   
   namespace :api, defaults: {format: 'json'} do
    namespace :v1 do
      resources :beacons
      resources :histories do
        collection do
          post :log
        end
      end
      resources :users do
        collection do
          post :logout
        end
      end
    end
  end

end

app/models/history.rb
class History < ActiveRecord::Base
  belongs_to :user_device
  belongs_to :user
  has_many :history_logs
end

app/controllers/api/v1/histories_controller.rb
module Api
	module V1 
		class HistoriesController < ApplicationController
			skip_before_action :authenticate_admin!
			skip_before_action :verify_authenticity_token
			def create
				history_temp = Array.new
				@user = User.find(params[:user_id])
				if params[:history] && params[:history] !=""
					history_params = ActiveSupport::JSON.decode(params[:history])
					puts history_params
					history_params['data'].each do |item|
						h = History.new
						h.entry_time	= item['entry_time']
						h.exit_time	= item['exit_time']
						h.user_device_id = item['user_device_id']
						h.user_id = params[:user_id]
						h.random_number = item['random_number']
						h.save
						history_temp << h
					end	
					render :json => { action: "history_add",
                        # http://tools.ietf.org/html/rfc6749#section-5.1
                        response: "true",
                        message: "history added successfully",
                        is_active: @user.is_active.to_s, 
                        access_permission:  @user.access_permission.to_s,
                        history_stored: history_temp}
		        else
		        	render :json => { action: "history_add",
                        # http://tools.ietf.org/html/rfc6749#section-5.1
                        response: "false",
                        message: "History was not added."}
				end
			end

			def log
				history_temp = Array.new
				@user = User.find(params[:user_id])
				if params[:history] && params[:history] !=""
					history_params = ActiveSupport::JSON.decode(params[:history])
					puts history_params
					history_params['data'].each do |item|
						# adding history parameter in history table
						if History.exists?(random_number: item['random_number'])
						  # your History id exists in the database
 							etime = item['exit_time']
						  	if (etime.present?)
						  		History.where(:random_number => item['random_number']).update_all(exit_time: etime)
						  	end
						  	# finding history id where history log need to be create
							# h  = History.where(["random_number = ?", item['random_number']]).take
							h = History.where(random_number: item['random_number']).take 
						else
						  # the History id doesn't exists
							h = History.new
							h.entry_time	= item['entry_time']
							h.exit_time	= item['exit_time']
							h.user_device_id = item['user_device_id']
							h.user_id = params[:user_id]
							h.random_number = item['random_number']
							h.save
						end
						# finding history id where history log need to be create
							h_id  = History.where(["random_number = ?", item['random_number']]).select('id').first
						# checking history log if exists removeing it
						if HistoryLog.exists?(history_id: h_id)
							HistoryLog.delete_all(history_id: h_id)
						end
						
						# creating history log
						item['historty_logs'].each do |l|
							h_log = HistoryLog.new
							h_log.history_id = h_id['id']
							h_log.random_number = l['random_number']
							h_log.log_time = l['log_time']
							h_log.log_type = l['log_type']
							h_log.log_description = l['log_description']
							h_log.save
						end
						history_temp << h
					end	
					render :json => { action: "history_add",
                        # http://tools.ietf.org/html/rfc6749#section-5.1
                        response: "true",
                        message: "history added successfully",
                        is_active: @user.is_active.to_s, 
                        access_permission:  @user.access_permission.to_s,
                        history_stored: history_temp}
		        else
		        	render :json => { action: "history_add",
                        # http://tools.ietf.org/html/rfc6749#section-5.1
                        response: "false",
                        message: "History was not added."}
				end
			end

	  	private
	  		def user_params
		    params.require(:history).permit(:entry_time,:exit_time, :user_device_id, :data[])
		   end
		end
	end
end

app/controllers/histories_controller.rb
class HistoriesController < ApplicationController
  
  def index
    @histories = History.order('id DESC').paginate(:page => params[:page], :per_page => 10 )
  end
  def show
    @history = History.find(params[:id])
  end
  def search
    @user = User.where(email: params[:email]).first
    #  @histories = ""
    # if @user.blank?
    #   @histories = ""
    # else
    #   @user.user_devices.each do |d|
    #     # @histories << d.histories
    #   end
    # end
    # render :template => "histories/index"
  end  
end

app/views/histories/index.html.erb
  <!-- page content -->
    <div class="right_col" role="main">
      <div class="">
        <div class="page-title">
          <div class="title_left">
            <h3>All History</h3>
          </div>
          <div class="title_right">
            <div class="col-md-5 col-sm-5 col-xs-12 form-group pull-right top_search">
              <div class="input-group">
              <%#= form_for search_histories_path do |f| %>
                <input type="text" class="form-control" placeholder="enter user email.." id = "email">
                    <span class="input-group-btn">

                      <button class="btn btn-default" type="button" id = "search">Go!</button>
                    </span>
                <%# end %>
              </div>
            </div>
          </div>
        </div>
        <div class="row">
          <div class="clearfix"></div>
          <div class="col-md-12 col-sm-12 col-xs-12">
            <div class="x_panel" style="height:600px;">
              <div class="x_title">
                <h2>History </h2>
                <ul class="nav navbar-right panel_toolbox">
                  <li><a class="collapse-link"><i class="fa fa-chevron-up"></i></a>
                  </li>
                  <li><a class="close-link"><i class="fa fa-close"></i></a>
                  </li>
                </ul>
                <div class="clearfix"></div>
              </div>
              <div class="x_content table-responsive">
               
                <table class="table table-striped responsive-utilities jambo_table bulk_action">
                  <thead>
                    <tr class="headings">
                      <th class="column-title">Entry Time </th>
                      <th class="column-title">Exit Time </th>
                      <th class="column-title">User Device Name </th>
                      <th class="column-title">User Name </th>   
                      <th class="column-title no-link last"><span class="nobr">Action</span> </th>                  
                    </tr>
                  </thead>
                  <% if !@histories.blank? %>
                   <% @histories.each do |h| %>
                    <tbody>
                      <tr class="even pointer">
                        <td class=" "><%= h.entry_time.to_s.sub('UTC' , '') %></td>
                        <td class=" "><%= h.exit_time.to_s.sub('UTC' , '') %></td>
                        <td class=" "><%= h.user_device.name %></td>
                        <td class=" "><%= h.user.first_name.titleize + ' ' + h.user.last_name.titleize  %></td>
                        <td class=" last">
                        <%= link_to '<i class="fa fa-info-circle"></i>'.html_safe, h,  style: "margin-right: 10px;" %> </td>
                      </tr>
                    </tbody>
                   <% end %>
                  <% end %>
                </table>
                <div>
                <%= will_paginate @historie %>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
    <!-- /page content -->
  

  

  <script type="text/javascript">
    $('#search').click(function() {
       // $.ajax({
       //  url: "<%= search_histories_path %>",
       //  type: "GET",
       //  data: {"email" : $('#email').val()},
       //  headers: {
       //    'X-CSRF-Token': '<%= form_authenticity_token.to_s %>'
       //  },
       //  dataType: "html",
       //  success: function(data) {
          window.location.href = "/histories/search?email="+ $('#email').val()
          
      //   }
      // });
    });
</script>

app/views/histories/search.html.erb
  <!-- page content -->
    <div class="right_col" role="main">
      <div class="">
        <div class="page-title">
          <div class="title_left">
            <h3>All History</h3>
          </div>
          <div class="title_right">
            <div class="col-md-5 col-sm-5 col-xs-12 form-group pull-right top_search">
              <div class="input-group">
              <%#= form_for search_histories_path do |f| %>
                <input type="text" class="form-control" placeholder="enter user email.." id = "email">
                    <span class="input-group-btn">

                      <button class="btn btn-default" type="button" id = "search">Go!</button>
                    </span>
                <%# end %>
              </div>
            </div>
          </div>
        </div>
        <div class="row">
          <div class="clearfix"></div>
          <div class="col-md-12 col-sm-12 col-xs-12">
            <div class="x_panel" style="height:600px;">
              <div class="x_title">
                <h2>History </h2>
                <ul class="nav navbar-right panel_toolbox">
                  <li><a class="collapse-link"><i class="fa fa-chevron-up"></i></a>
                  </li>
                  <li><a class="close-link"><i class="fa fa-close"></i></a>
                  </li>
                </ul>
                <div class="clearfix"></div>
              </div>
              <div class="x_content table-responsive">
               
                <table class="table table-striped responsive-utilities jambo_table bulk_action">
                  <thead>
                    <tr class="headings">
                      <th class="column-title">Entry Time </th>
                      <th class="column-title">Exit Time </th>
                      <th class="column-title">User Device Name </th>
                      <th class="column-title">User Name </th>                      
                    </tr>
                  </thead>
                  <% if !@user.blank?
                    @user.user_devices.each do |d| 
                    if !d.blank? %>
                    <% if !d.histories.blank? %>
                     <% d.histories.each do |h| %>
                      <tbody>
                        <tr class="even pointer">
                          <td class=" "><%= h.entry_time.to_s.sub('UTC' , '') %></td>
                          <td class=" "><%= h.exit_time.to_s.sub('UTC' , '') %></td>
                          <td class=" "><%= h.user_device.name %></td>
                          <td class=" "><%= h.user_device.user.first_name.titleize + ' ' + h.user_device.user.last_name.titleize  %></td>
                        </tr>
                      </tbody>
                     <% end %>
                  <% end 
                  end  
                  end  
                  end%>
                </table>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
    <!-- /page content -->
  

  

  <script type="text/javascript">
    $('#search').click(function() {
       // $.ajax({
       //  url: "<%= search_histories_path %>",
       //  type: "GET",
       //  data: {"email" : $('#email').val()},
       //  headers: {
       //    'X-CSRF-Token': '<%= form_authenticity_token.to_s %>'
       //  },
       //  dataType: "html",
       //  success: function(data) {
          window.location.href = "/histories/search?email="+ $('#email').val()
          
      //   }
      // });
    });
</script>

app/views/histories/show.html.erb
<!-- page content -->
<div class="right_col" role="main">
  <div class="">
    <div class="page-title">
      <div class="title_left">
        <h3>All History</h3>
      </div>
    </div>
    <div class="row">
    	<div class="clearfix"></div>
      <div class="col-md-10 col-sm-12 col-xs-12">
        <div class="x_panel">
          <div class="x_title">
            <h2>History Information</h2>
            <ul class="nav navbar-right panel_toolbox">
              <li><a class="collapse-link"><i class="fa fa-chevron-up"></i></a>
              </li>
              <li><a class="close-link"><i class="fa fa-close"></i></a>
              </li>
            </ul>
            <div class="clearfix"></div>
          </div>
          <!-- <div class="x_content"><br />
          	<div class="form-group">
          		<div class="control-label col-md-3 col-sm-3 col-xs-12">
             <%#= label_tag :Entry_Time %>
            </div>
            <div class="col-md-9 col-sm-9 col-xs-12">
                <%= @history.entry_time %>
            </div>
           </div>
         </div>
         <div class="x_content"><br />
         <div class="form-group">
          	<div class="control-label col-md-3 col-sm-3 col-xs-12">
             <%#= label_tag :Exit_Time %>
            </div>
            <div class="col-md-9 col-sm-9 col-xs-12">
                <%= @history.exit_time %>
            </div>
         </div>
         </div>
         <div class="x_content"><br />
         <div class="form-group">
	          <div class="control-label col-md-3 col-sm-3 col-xs-12">
	            <%#= label_tag :User_Device_Name %>
	          </div>
           	<div class="col-md-9 col-sm-9 col-xs-12">
                <%=@history.user_device.name %>
            </div>
         </div>
				 </div> -->
         <div class="x_content"><br />
         <div class="form-group">
            <div class="control-label col-md-3 col-sm-3 col-xs-12">
             <%= label_tag :history_logs %>
            </div>
         </div>
         </div>
          <div class="x_content table-responsive">
               
                <table class="table table-striped responsive-utilities jambo_table bulk_action">
                  <thead>
                    <tr class="headings">
                      <th class="column-title">Log Time </th>
                      <th class="column-title">Log Type </th>
                      <th class="column-title">Log Description </th>   
                                     
                    </tr>
                  </thead>
                  <% if !@history.history_logs.blank? %>
                   <% @history.history_logs.each do |lh| %>
                    <tbody>
                      <tr class="even pointer">
                        <td class=" "><%= lh.log_time.to_s.sub('UTC' , '') %></td>
                        <td class=" "><%= lh.log_type %></td>
                        <td class=" "><%= lh.log_description %></td>
                                              
                      </tr>
                    </tbody>
                   <% end %>
                  <% end %>
                </table>   
              </div>
				</div>
      </div>    
    </div>
  </div>
</div>


   