config/routes.rb
Rails.application.routes.draw do
  
  mount_opro_oauth
  
  devise_for :admins

   root 'plainpage#home'
   resources :plainpage
   resources :settings
   resources :users
   resources :user_devices
   resources :beacons
   resources :admins
   resources :histories do
     collection do
      get :search
     end
   end
   
   namespace :api, defaults: {format: 'json'} do
    namespace :v1 do
      resources :beacons
      resources :histories do
        collection do
          post :log
        end
      end
      resources :users do
        collection do
          post :logout
        end
      end
    end
  end

end

app/controllers/settings_controller.rb
class SettingsController < ApplicationController
	def create
	
	end
	def edit
	 @timer = RssiTimer.find(1)
	end
	def update
	 @timer = RssiTimer.find(1)
	 @timer.timer_value = params[:timer_value]
	 @timer.timer_value2 = params[:timer_value2]
	 @timer.rssiLimit = params[:rssiLimit]
	 @timer.save
	 redirect_to root_url
	end

end
	

app/views/settings/edit.html.erb
<!-- page content -->

<div class="right_col" role="main">
  <div class="">
    <div class="page-title">
      <div class="title_left">
        <h3>Setting</h3>
      </div>
    </div>
    <div class="row">
      <div class="clearfix"></div>
      <div class="col-md-10 col-sm-12 col-xs-12">
        <div class="x_panel" style="height:600px;">
          <div class="x_title">
            <h2>Time Setting</h2>
            <ul class="nav navbar-right panel_toolbox">
              <li><a class="collapse-link"><i class="fa fa-chevron-up"></i></a>
              </li>
              <li><a class="close-link"><i class="fa fa-close"></i></a>
              </li>
            </ul>
            <div class="clearfix"></div>
          </div>
          <div class="x_content"><br />
          <%= form_tag setting_path(@timer),:html => { :multipart => true ,:class=>'form-horizontal form-label-left input_mask'}, :method => :put do %>
            <%#= form_for @timer, :html => { :multipart => true ,:class=>'form-horizontal form-label-left input_mask'} do |f| %>
             <div class="form-group">
                <%= label_tag 'timer_value',"Max delay to pass the door 1", class: "control-label col-md-3 col-sm-3 col-xs-12" %>

                <div class="col-md-6 col-sm-9 col-xs-12">
                  <%= number_field_tag 'timer_value', @timer.timer_value, class: "form-control", in: 10...301 %>
                  [ Enter value between 10 to 300 ]
                </div>
              </div></br></br></br></br></br>
              <div class="form-group">
                <%= label_tag 'timer_value2',"Max delay to pass the door 2", class: "control-label col-md-3 col-sm-3 col-xs-12" %>

                <div class="col-md-6 col-sm-9 col-xs-12">
                  <%= number_field_tag 'timer_value2', @timer.timer_value2, class: "form-control", in: 10...301 %>
                  [ Enter value between 10 to 300 ]
                </div>
              </div></br></br></br></br></br>

             <!-- hardik -->

              <div class="form-group">
                <%= label_tag 'rssiLimit',"Thresold RSSI", class: "control-label col-md-3 col-sm-3 col-xs-12" %>

                <div class="col-md-6 col-sm-9 col-xs-12">
                  <%= number_field_tag 'rssiLimit', @timer.rssiLimit, class: "form-control", in: -99...-1 %>
                  [ Enter value between -99 to -1 ]
                </div>
              </div></br></br></br>
<!--  -->

           
              <!-- <div class="form-group">
                <%#= label_tag :timer_value,  class: "control-label col-md-3 col-sm-3 col-xs-12" %>
                <div class="col-md-6 col-sm-9 col-xs-12">
                  <%#= text_field_tag :timer_value, required: true %>
                </div>
              </div> -->
             
              <div class="ln_solid"></div>
              <div class="form-group">
                <div class="col-md-9 col-sm-9 col-xs-12 col-md-offset-3">
                  <%= link_to "Cancel", :back, {:class=>"btn btn-primary"} %>
                  <button type="submit" class="btn btn-success">Submit</button>
                </div>
              </div>
            
            <% end %>
          </div>
        </div> 
      </div>    
    </div>
  </div>
</div>


   